# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: netflix-app
#   labels:
#     app: netflix-app
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: netflix-app
#   template:
#     metadata:
#       labels:
#         app: netflix-app
#     spec:
#       containers:
#       - name: netflix-app
#         image: mehta7/netflix:latest
#         ports:
#         - containerPort: 80
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: thetips4you/nodeapp:latest
        ports:
        - containerPort: 3000
